namespace SDK.PC{
    public class LanguageModel : BaseModel{
        public string tds_account_safe_info { get; set; }
        public string tds_account_info { get; set; }
        public string tds_account_bind_info { get; set; }
        public string tds_unbind { get; set; }
        public string tds_bind { get; set; }
        public string tds_guest { get; set; }
        public string tds_delete_account_title { get; set; }
        public string tds_unbind_account_title { get; set; }
        public string tds_delete_account_sure_title { get; set; }
        public string tds_delete_account { get; set; }
        public string tds_unbind_account { get; set; }
        public string tds_unbind_account_button { get; set; }
        public string tds_delete_account_sure { get; set; }
        public string tds_delete_content { get; set; }
        public string tds_unbind_content { get; set; }
        public string tds_unbind_delete_content { get; set; }
        public string tds_unbind_confirm_Content { get; set; }
        public string tds_delete_confirm_content { get; set; }
        public string tds_input_error { get; set; }
        public string tds_cancel { get; set; }
        public string tds_input_error_re { get; set; }
        public string tds_confirm { get; set; }
        public string tds_delete { get; set; }
        public string tds_loading { get; set; }
        public string tds_current_account_prefix { get; set; }
        public string tds_account_format { get; set; }
        public string tds_current_id { get; set; }
        public string tds_copy_success { get; set; }
        public string tds_cancel_bind { get; set; }
        public string tds_unbind_error { get; set; }
        public string tds_bind_error_reason_format { get; set; }
        public string tds_bind_error { get; set; }
        public string tds_bind_success { get; set; }
        public string tds_unbind_success { get; set; }
        public string tds_unbind_success_return_sign { get; set; }
        public string tds_unbind_delete_success_return_sign { get; set; }
        public string tds_unbind_guest_return { get; set; }
        public string tds_loading_error_retry { get; set; }
        public string tds_network_error_retry { get; set; }
        public string tds_login_success { get; set; }
        public string tds_login_cancel { get; set; }
        public string tds_login_failed { get; set; }
        public string tds_login_button_title { get; set; }
        public string tds_logout { get; set; }
        public string tds_authorization_cancel { get; set; }
        public string tds_authorization_failed { get; set; }
        public string tds_network_error_login { get; set; }
        public string tds_network_error_safe_retry { get; set; }
        public string tds_refund_custom_service_tip { get; set; }
        public string tds_refund_contact_custom_service { get; set; }
        public string tds_refund_custom_service_tip_tail { get; set; }
        public string tds_refund_success { get; set; }
        public string tds_refund_fail { get; set; }
        public string tds_refund_cancel { get; set; }
        public string tds_refund_action { get; set; }
        public string tds_refund_login_restrict_title { get; set; }
        public string tds_refund_login_restrict_sub_title { get; set; }
        public string tds_refund_ios_pay_tip { get; set; }
        public string tds_pay_success { get; set; }
        public string tds_pay_fail { get; set; }
        public string tds_pay_cancel { get; set; }
        public string tds_button_confirm { get; set; }
        public string tds_promotion_exchange_title { get; set; }
        public string tds_promotion_exchange_desc { get; set; }
        public string tds_refund_android_pay_tip { get; set; }
        public string tds_pay_net_fail { get; set; }
        public string tds_refund_net_fail { get; set; }
        public string tds_purchase_processing { get; set; }
        public string tds_terms_agreement { get; set; }
        public string tds_service_terms_agreement { get; set; }
        public string tds_push_agreement { get; set; }
        public string tds_confirm_agreement { get; set; }
        public string tds_is_adult_agreement { get; set; }
        public string tds_california_agreement { get; set; }
        public string tds_cancel_claim { get; set; }
        public string tds_custom_service { get; set; }
        public string tds_product_not_exists { get; set; }
        public string tds_ios_restricted_payment_title { get; set; }
        public string tds_ios_restricted_payment_description { get; set; }
    }
}